
sudo: required

services:
  - docker

script:
  - docker build -t dselck/docked-python:latest .
  - docker ps -a
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dselck/docked-python:latest;
    fi